[pytest]
rp_endpoint = https://reportportal.epam.com
rp_api_key  = pytest-key_iRsnpXV8RYqrhewGUhk7VdYaE7HfrMPpKjqhB4uW6Ypy8_r-ooC-TuoVfWvQJzrZ
rp_project = mangesh_kapgate_personal
rp_launch = DQ_Automation_Run
rp_log_batch_size = 20



# Only run files starting with test_
python_files = test_*.py

# marks
markers =
    validate_csv: CSV tests
    unmarked: tests without marks
    prefix_test: files with prefix text_
# python_files
# addopts