pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install -r pytest_dq_framework/requirements.txt
                pip install psycopg2-binary
                '''
            }
        }

        stage('Run Data Pipeline') {
            steps {
                sh '''
                . venv/bin/activate
                python data_dev/main.py
                '''
            }
        }

        stage('Run Pytest') {
            steps {
                sh '''
                . venv/bin/activate
                pytest pytest_dq_framework/tests --html=pytest_dq_framework/report.html
                '''
            }
        }

    }
}